In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv("C:\Users\Shubham\OneDrive\Desktop\Wac_may-18_ML\day 7\titanic datasettrain.csv")

FileNotFoundError: [Errno 2] File //train.csv does not exist: '//train.csv'

In [13]:
df.head()

NameError: name 'df' is not defined

In [0]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [0]:
l1 = ['PassengerId', 'Cabin', 'Ticket']
df.drop(l1, inplace= True, axis = 1)

In [0]:
df.head()

Survived  Pclass  ...     Fare Embarked
0         0       3  ...   7.2500        S
1         1       1  ...  71.2833        C
2         1       3  ...   7.9250        S
3         1       1  ...  53.1000        S
4         0       3  ...   8.0500        S

[5 rows x 9 columns]

In [0]:
temp  = df["Name"].unique()

In [0]:
temp[:10]

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)'], dtype=object)

In [0]:
st = []

for i in temp :
    a = i.split(' ')
    for k in a :
        if '.' in k:
            st.append(k)
            break

In [0]:
st = np.array(st)
df["New_Name"] = st

In [0]:
df.head()

Survived  Pclass  ... Embarked New_Name
0         0       3  ...        S      Mr.
1         1       1  ...        C     Mrs.
2         1       3  ...        S    Miss.
3         1       1  ...        S     Mrs.
4         0       3  ...        S      Mr.

[5 rows x 10 columns]

In [0]:
df["New_Name"].unique()

array(['Mr.', 'Mrs.', 'Miss.', 'Master.', 'Don.', 'Rev.', 'Dr.', 'Mme.',
       'Ms.', 'Major.', 'Lady.', 'Sir.', 'Mlle.', 'Col.', 'Capt.',
       'Countess.', 'Jonkheer.'], dtype=object)

In [0]:
l2 = ['Name']
df.drop(l2, axis = 1, inplace = True)

In [0]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked New_Name
0         0       3    male  22.0      1      0   7.2500        S      Mr.
1         1       1  female  38.0      1      0  71.2833        C     Mrs.
2         1       3  female  26.0      0      0   7.9250        S    Miss.
3         1       1  female  35.0      1      0  53.1000        S     Mrs.
4         0       3    male  35.0      0      0   8.0500        S      Mr.

In [0]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
New_Name      0
dtype: int64

In [0]:
emb = list(df["Embarked"].mode())[0]
df["Age"].fillna(df["Age"].mean(), inplace = True)
df["Embarked"].fillna(emb, inplace = True)

In [0]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
New_Name    0
dtype: int64

In [0]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
le_embarked = LabelEncoder()
le_newName = LabelEncoder()

In [0]:
df["Sex"] = le_sex.fit_transform(df["Sex"])
df["Embarked"] = le_embarked.fit_transform(df["Embarked"])
df["New_Name"] = le_newName.fit_transform(df["New_Name"])

In [0]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  New_Name
0         0       3    1  22.0      1      0   7.2500         2        12
1         1       1    0  38.0      1      0  71.2833         0        13
2         1       3    0  26.0      0      0   7.9250         2         9
3         1       1    0  35.0      1      0  53.1000         2        13
4         0       3    1  35.0      0      0   8.0500         2        12

In [0]:
df.shape

(891, 9)

In [0]:
X = df.iloc[:, 1:].values
y = df.iloc[:, 0].values

In [0]:
X.shape, y.shape

((891, 8), (891,))

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1)

In [0]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((801, 8), (801,), (90, 8), (90,))

In [0]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

In [0]:
from sklearn.ensemble import RandomForestClassifier

In [0]:
clf = RandomForestClassifier(n_estimators= 50, n_jobs= -1, max_depth= 3)

In [0]:
clf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=3, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=-1,
                       oob_score=False, random_state=None, verbose=0,
                       warm_start=False)

In [0]:
pred = clf.predict(X_test)

In [0]:
clf.score(X_train, y_train)

0.8227215980024969

In [0]:
clf.score(X_test, y_test)

0.7888888888888889

In [0]:
from sklearn.metrics import confusion_matrix

In [0]:
print(confusion_matrix(pred, y_test))

[[51 13]
 [ 6 20]]


In [0]:
y_test.shape

(90,)

# Boosting

In [0]:
from sklearn.ensemble import AdaBoostClassifier

In [0]:
clf1 = AdaBoostClassifier(n_estimators= 50, learning_rate= 0.3)

In [0]:
clf1.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=0.3,
                   n_estimators=50, random_state=None)

In [0]:
pred1 = clf1.predict(X_test)

In [0]:
clf1.score(X_train, y_train)

0.8239700374531835

In [0]:
clf1.score(X_test, y_test)

0.8333333333333334

In [0]:
print(confusion_matrix(pred1, y_test))

[[48  6]
 [ 9 27]]


In [0]:
from xgboost import XGBClassifier

In [0]:
clf3 = XGBClassifier(n_estimators= 10, n_jobs= -1, learning_rate=0.1)

In [0]:
clf3.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=10, n_jobs=-1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [0]:
pred2 = clf3.predict(X_test)

In [0]:
clf3.score(X_train, y_train)

0.8339575530586767

In [0]:
clf3.score(X_test, y_test)

0.8

In [0]:
print(confusion_matrix(pred2, y_test))

[[52 13]
 [ 5 20]]


In [0]:
from sklearn.metrics import classification_report
print(classification_report(pred2, y_test))

              precision    recall  f1-score   support

           0       0.91      0.80      0.85        65
           1       0.61      0.80      0.69        25

    accuracy                           0.80        90
   macro avg       0.76      0.80      0.77        90
weighted avg       0.83      0.80      0.81        90



In [0]:
(2*0.91*0.80)/(0.91+0.80)

0.8514619883040937

In [0]:
(2*0.61*0.80)/(0.61+0.80)

0.6921985815602836

CV and Grid Search

In [0]:
from sklearn.model_selection import cross_val_score

In [0]:
cross_val_score(clf3, X_train, y_train, cv = 5, n_jobs= -1).mean()

0.8202173913043478

In [0]:
#hyper parameter tunning
from sklearn.model_selection import GridSearchCV

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=10, n_jobs=-1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [0]:
param = {
    "learning_rate" : [0.1, 0.01, 0.3, 0.6, 0.5],
    "max_depth" : [1,2,3,4],
    "n_estimators" : [5, 10, 15, 20],
}

In [0]:
clf_grid = GridSearchCV(estimator= clf3, param_grid= param, n_jobs= -1, cv= 3)

In [0]:
clf_grid.fit(X_train, y_train)

GridSearchCV(cv=3, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0,
                                     learning_rate=0.1, max_delta_step=0,
                                     max_depth=3, min_child_weight=1,
                                     missing=None, n_estimators=10, n_jobs=-1,
                                     nthread=None, objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, seed=None, silent=None,
                                     subsample=1, verbosity=1),
             iid='deprecated', n_jobs=-1,
             param_grid={'learning_rate': [0.1, 0.01, 0.3, 0.6, 0.5],
                         'max_depth': [1, 2, 3, 4],
                         'n_estimators': [5, 10, 15, 20]}

In [0]:
clf_grid.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.3, max_delta_step=0, max_depth=4,
              min_child_weight=1, missing=None, n_estimators=10, n_jobs=-1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [0]:
clf_grid.best_params_

{'learning_rate': 0.3, 'max_depth': 4, 'n_estimators': 10}

In [0]:
clf_grid.best_score_

0.83270911360799