# Numpy

In [0]:
import numpy as np

In [0]:
a = np.array(list(range(10)))

In [0]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
type(a)

numpy.ndarray

In [0]:
b = a + 5
b

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
c = a - 10
c

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

In [0]:
a*5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [0]:
a/5

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [0]:
a**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [0]:
c.shape

(10,)

In [0]:
c = c.reshape((-1, 1))

In [0]:
c.shape

(10, 1)

ARRAY OPERATIONS

In [0]:
print(a)
print(b)
a+b

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [0]:
a-b

array([-5, -5, -5, -5, -5, -5, -5, -5, -5, -5])

In [0]:
a*b

array([  0,   6,  14,  24,  36,  50,  66,  84, 104, 126])

In [0]:
a/b

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444,
       0.5       , 0.54545455, 0.58333333, 0.61538462, 0.64285714])

In [0]:
a**b

array([             0,              1,            128,           6561,
               262144,        9765625,      362797056,    13841287201,
         549755813888, 22876792454961])

In [0]:
a+c

array([[-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1],
       [ -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0],
       [ -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1],
       [ -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2],
       [ -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3],
       [ -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4],
       [ -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5],
       [ -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6],
       [ -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7],
       [ -1,   0,   1,   2,   3,   4,   5,   6,   7,   8]])

In [0]:
print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[[-10]
 [ -9]
 [ -8]
 [ -7]
 [ -6]
 [ -5]
 [ -4]
 [ -3]
 [ -2]
 [ -1]]


In [0]:
d = np.array([[1,2,3], [4,5,6]])

In [0]:
d

array([[1, 2, 3],
       [4, 5, 6]])

## Functions of numpy

In [0]:
a = np.zeros((3,4), dtype= "int")
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [0]:
e = np.zeros((3,3,3))
e

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [0]:
print(e)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [0]:
s = np.array(["shubham", "anmol", "nitish"])
s

array(['shubham', 'anmol', 'nitish'], dtype='<U7')

In [0]:
print(s)

['shubham' 'anmol' 'nitish']


In [0]:
a = np.ones((4,3), dtype= "int")
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [0]:
a = np.eye(4, )
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
a = np.ones((4,3), dtype= "int")
a*5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

## Random Functions

In [0]:
np.random.randint(1,10)

4

In [0]:
a = np.random.randint(1,10, (3,4))

In [0]:
print(a)

[[1 6 3 4]
 [5 5 7 5]
 [4 7 8 9]]


In [0]:
a.shape

(3, 4)

In [0]:
a[ 1:, 1:3]

array([[5, 7],
       [7, 8]])

## More functions
min, max, mean, variance, std

In [0]:
a = np.array([[1, 3], [4,2]])
a

array([[1, 3],
       [4, 2]])

In [0]:
a.min()

1

In [0]:
a.max()

4

In [0]:
np.min(a)

1

In [0]:
np.std(a, axis = 1)

array([1., 1.])

In [0]:
np.var(a, axis = 1)

array([1., 1.])

In [0]:
np.random.seed(7)
np.random.randint(10)

4

In [0]:
for i in range(10) :
    # np.random.seed(7)
    print(np.random.randint(10))

9
6
3
3
7
7
9
7
8
9


In [0]:
a  = np.array([1,2,3])
b = np.array([3, 4, 5])

In [0]:
np.stack((b,a), axis = 1)

array([[3, 1],
       [4, 2],
       [5, 3]])