In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
X_train = pd.read_csv("train.csv")

In [3]:
X_train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [4]:
X_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [0]:
l1 = ['PassengerId', "Name", "Ticket"]
X_train.drop(l1, axis = 1, inplace = True)

In [7]:
X_train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [8]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object 
 8   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB


In [10]:
l2 = ["Cabin"]
X_train.drop(l2, axis=1, inplace = True)
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [11]:
X_train.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [28]:
emb_fill = list(X_train["Embarked"].mode())[0]
print(emb_fill)
print(type(emb_fill))
X_train["Age"].fillna(X_train["Age"].mean(), inplace = True)
X_train["Embarked"].fillna(emb_fill, inplace = True)

S
<class 'str'>


In [22]:
X_train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [23]:
X_train.shape

(891, 8)

In [24]:
X_train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [0]:
from sklearn.preprocessing import LabelEncoder
le_g = LabelEncoder()
le_e = LabelEncoder()

In [0]:
X_train["Sex"] = le_g.fit_transform(X_train["Sex"])
X_train["Embarked"] = le_e.fit_transform(X_train["Embarked"])

In [32]:
X_train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [42]:
X = X_train.iloc[:, 1:].values
Y = X_train.iloc[:, 0].values
X.shape, Y.shape

((891, 7), (891,))

In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [44]:
X[:5]

array([[ 0.82737724,  0.73769513, -0.5924806 ,  0.43279337, -0.47367361,
        -0.50244517,  0.58595414],
       [-1.56610693, -1.35557354,  0.63878901,  0.43279337, -0.47367361,
         0.78684529, -1.9423032 ],
       [ 0.82737724, -1.35557354, -0.2846632 , -0.4745452 , -0.47367361,
        -0.48885426,  0.58595414],
       [-1.56610693, -1.35557354,  0.40792596,  0.43279337, -0.47367361,
         0.42073024,  0.58595414],
       [ 0.82737724,  0.73769513,  0.40792596, -0.4745452 , -0.47367361,
        -0.48633742,  0.58595414]])

In [0]:
from sklearn.linear_model import LogisticRegression

In [0]:
clf = LogisticRegression(solver= 'sag' ,n_jobs= -1)

In [56]:
clf.fit(X, Y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=-1, penalty='l2',
                   random_state=None, solver='sag', tol=0.0001, verbose=0,
                   warm_start=False)

In [0]:
Y_pred = clf.predict(X)

In [58]:
clf.score(X, Y)

0.8002244668911336

In [0]:
from sklearn.metrics import confusion_matrix

In [61]:
print(confusion_matrix(Y_pred, Y))

[[474 103]
 [ 75 239]]


# SVM

In [0]:
from sklearn.svm import SVC

In [0]:
clf1 = SVC(C= 100, gamma= 1)

In [93]:
clf1.fit(X, Y)

SVC(C=100, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf', max_iter=-1,
    probability=False, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [0]:
pred_y1 = clf1.predict(X)

In [95]:
clf1.score(X, Y)

0.9135802469135802

In [96]:
print(confusion_matrix(pred_y1, Y))

[[517  45]
 [ 32 297]]


In [70]:
print(confusion_matrix(Y_pred, Y))

[[474 103]
 [ 75 239]]


In [0]:
pred_y1 = pd.DataFrame(pred_y1)

In [0]:
pred_y1.to_csv("answer")